Repository hyperledger-labs/fabric-token-sdk, pull requests merged in 2022-09, with the labels that each got.

#368 check public parameters match
  integration/token/fungible/tests.go
  integration/token/fungible/topology.go
  integration/token/fungible/views/info.go
  token/core/fabtoken/driver/driver.go
  token/core/fabtoken/loaders.go
  token/core/fabtoken/ppm.go
  token/core/fabtoken/service.go
  token/core/zkatdlog/crypto/ppm/ppm.go
  token/core/zkatdlog/crypto/setup.go
  token/core/zkatdlog/crypto/setup_test.go
  token/core/zkatdlog/crypto/testdata/idemix/msp/IssuerPublicKey
  token/core/zkatdlog/nogh/deserializer.go
  token/core/zkatdlog/nogh/driver/driver.go
  token/core/zkatdlog/nogh/loaders.go
  token/core/zkatdlog/nogh/service.go
  token/driver/publicparams.go
  token/publicparams.go
Labels: enhancement

#360 Interop documentation
  docs/interop.md
Labels: documentation

#380 remove "zkat" magic string #107
  integration/nwo/token/topology.go
  token/sdk/network/normalizer.go
  token/services/network/fabric/processor.go
  token/services/network/orion/processor.go
  token/services/ttx/transaction.go
  token/services/vault/keys/keys.go
  token/services/vault/translator/translator_test.go
Labels: cleanup

#379 ScanForPreImage Enhancement: Custom Starting Point #378
  integration/token/interop/support.go
  integration/token/interop/tests.go
  integration/token/interop/views/htlc/scan.go
  token/services/interop/htlc/scanner.go
  token/tms.go
Labels: enhancement

#369 htlc auditing extension
  go.sum
  integration/token/interop/views/auditor.go
  integration/token/interop/views/htlc/lock.go
  token/core/fabtoken/sender.go
  token/core/fabtoken/validator_transfer.go
  token/core/interop/htlc/info.go
  token/core/zkatdlog/crypto/validator/validator_transfer.go
  token/core/zkatdlog/nogh/sender.go
  token/request.go
  token/services/interop/htlc/audit.go
  token/services/interop/htlc/script.go
  token/services/interop/htlc/signer.go
  token/services/interop/htlc/wallet.go
  token/stream.go
Labels: enhancement

#376 Export `ttxdb` SetStatus function
  integration/token/fungible/dloghsm/topology.go
  integration/token/fungible/tests.go
  integration/token/fungible/topology.go
  integration/token/fungible/views/auditor.go
  integration/token/fungible/views/transfer.go
  token/services/auditor/auditor.go
  token/services/ttx/auditor.go
Labels: enhancement

#381 double check the use of NewQuantityFromUInt64 #218
  integration/token/fungible/views/accept.go
  integration/token/fungible/views/issue.go
  integration/token/fungible/views/transfer.go
  samples/fungible/views/accept.go
  samples/fungible/views/issue.go
  token/core/fabtoken/issuer.go
  token/request.go
  token/services/nfttx/qe.go
  token/token/quantity.go
  token/token/quantity_test.go
Labels: cleanup

#382 review htlc terms
  go.mod
  go.sum
  integration/token/interop/views/htlc/exchange.go
  token/services/interop/htlc/distribute.go
Labels: enhancement

#384 Add timeout to Network Finality API #383
  go.mod
  go.sum
  integration/token/fungible/dloghsm/topology.go
  integration/token/fungible/tests.go
  integration/token/fungible/topology.go
  integration/token/fungible/views/transfer.go
  token/services/interop/htlc/finality.go
  token/services/interop/htlc/ordering.go
  token/services/network/driver/network.go
  token/services/network/fabric/network.go
  token/services/network/network.go
  token/services/network/orion/network.go
  token/services/nfttx/views.go
  token/services/ttx/finality.go
  token/services/ttx/ordering.go
Labels: enhancement

#387 add metadata to issue action
  Makefile
  token/core/fabtoken/actions.go
  token/core/zkatdlog/crypto/issue/issue.go
Labels: enhancement
