Repository hyperledger-labs/fabric-token-sdk, pull requests merged in 2022-11, with the labels that each got.

#414 check that output's quantity is less or equal to max_value. #411
  integration/nwo/token/common/ppmgen.go
  integration/token/fungible/support.go
  integration/token/fungible/tests.go
  integration/token/fungible/topology.go
  integration/token/fungible/views/accept.go
  integration/token/fungible/views/auditor.go
  integration/token/fungible/views/issue.go
  token/core/cmd/pp/dlog/gen.go
  token/core/fabtoken/setup.go
  token/core/identity/registry.go
  token/core/zkatdlog/crypto/issue/issue.go
  token/core/zkatdlog/crypto/setup.go
  token/core/zkatdlog/crypto/transfer/transfer.go
  token/core/zkatdlog/nogh/deserializer.go
  token/request.go
  token/token/quantity.go
Labels: bug, enhancement

#417 FSC update
  go.mod
  go.sum
  token/services/network/orion/approval.go
  token/services/network/orion/lookupkey.go
  token/services/network/orion/rwset.go
  token/services/network/orion/spenttokens.go
Labels: dep update

#418 let the token driver decide how to marshal a token request
  token/core/fabtoken/service.go
  token/core/zkatdlog/nogh/service.go
  token/driver/tms.go
  token/driver/wallet.go
  token/request.go
Labels: enhancement

#420 cleanup token request metadata
  token/driver/request.go
Labels: cleanup

#421 deprecate balance queries
  go.mod
  go.sum
  integration/token/dvp/tests.go
  integration/token/dvp/topology.go
  integration/token/dvp/views/balance.go
  integration/token/fungible/dloghsm/topology.go
  integration/token/fungible/support.go
  integration/token/fungible/topology.go
  integration/token/fungible/views/balance.go
  integration/token/interop/support.go
  token/sdk/sdk.go
  token/services/query/client.go
  token/services/query/handler.go
Labels: cleanup

#416 more checks
  Makefile
  fungible.mk
  go.mod
  go.sum
  integration/token/fungible/dlog/dlog_test.go
  integration/token/fungible/dloghsm/topology.go
  integration/token/fungible/support.go
  integration/token/fungible/tests.go
  integration/token/fungible/topology.go
  integration/token/fungible/views/checks.go
  integration/token/fungible/views/info.go
  integration/token/fungible/views/list.go
  integration/token/interop/support.go
  integration/token/interop/tests.go
  integration/token/interop/topology.go
  integration/token/interop/views/htlc/claim.go
  integration/token/interop/views/htlc/exchange.go
  integration/token/interop/views/htlc/reclaim.go
  token/core/zkatdlog/nogh/deserializer.go
  token/driver/vault.go
  token/services/auditor/auditor.go
  token/services/interop/htlc/wallet.go
  token/services/network/fabric/network.go
  token/services/network/fabric/processor.go
  token/services/network/fabric/vault.go
  token/services/network/network.go
  token/services/network/orion/network.go
  token/services/network/orion/processor.go
  token/services/network/orion/querytokens.go
  token/services/network/orion/vault.go
  token/services/network/orion/views.go
  token/services/network/processor/common.go
  token/services/owner/owner.go
  token/services/ttxdb/db.go
  token/services/vault/keys/keys.go
  token/services/vault/query/query.go
Labels: enhancement

#426 Fix Audit Lock mechanism
  go.mod
  go.sum
  integration/token/fungible/views/auditor.go
  integration/token/interop/support.go
  integration/token/interop/tests.go
  integration/token/interop/views/auditor.go
  integration/token/interop/views/htlc/claim.go
  integration/token/interop/views/htlc/lock.go
  samples/fungible/views/auditor.go
  token/services/auditor/auditor.go
  token/services/interop/htlc/signer.go
  token/services/ttx/auditor.go
  token/services/ttxdb/db.go
Labels: bug

#403 Update Public Param
  go.mod
  go.sum
  integration/nwo/token/common/ppmgen.go
  integration/nwo/token/fabric/fabric.go
  integration/nwo/token/fabric/tcc.go
  integration/nwo/token/orion/orion.go
  integration/nwo/token/platform.go
  integration/token/fungible/dlog/dlog_test.go
  integration/token/fungible/fabtoken/fabtoken_test.go
  integration/token/fungible/support.go
  integration/token/fungible/tests.go
  integration/token/fungible/topology.go
  integration/token/fungible/views/auditor.go
  integration/token/fungible/views/info.go
  token/core/fabtoken/ppm.go
  token/core/zkatdlog/crypto/ppm/ppm.go
  token/driver/publicparams.go
  token/publicparams.go
  token/services/network/fabric/processor.go
Labels: enhancement
