Repository hyperledger-labs/fabric-token-sdk, pull requests merged in 2022-10, with the labels that each got.

#391 go1.18
  Makefile
  go.mod
  go.sum
  samples/README.md
  tools/go.mod
Labels: enhancement

#393 lock error when same hash is used for lock #392
  integration/token/interop/tests.go
  token/core/fabtoken/validator_transfer.go
  token/core/interop/htlc/validator.go
  token/core/zkatdlog/crypto/validator/validator_transfer.go
  token/services/interop/htlc/keys.go
  token/services/interop/htlc/transaction.go
  token/services/vault/translator/translator.go
Labels: bug, enhancement, interoperability

#398 missing underlying validation
  token/core/fabtoken/ppm.go
  token/core/zkatdlog/crypto/ppm/ppm.go
Labels: bug

#397 query transaction records by action type and status #396
  integration/token/fungible/tests.go
  integration/token/fungible/views/history.go
  token/services/ttxdb/db/badger/badger.go
  token/services/ttxdb/db/memory/memory.go
  token/services/ttxdb/driver/driver.go
Labels: enhancement

#395 Provide an efficient way to lookup wallet by ID #394
  token/core/fabtoken/driver/driver.go
  token/core/fabtoken/service.go
  token/core/fabtoken/wallet.go
  token/core/identity/registry.go
  token/core/identity/registry_test.go
  token/core/zkatdlog/nogh/auditor.go
  token/core/zkatdlog/nogh/certifier.go
  token/core/zkatdlog/nogh/driver/driver.go
  token/core/zkatdlog/nogh/service.go
  token/core/zkatdlog/nogh/wallet.go
Labels: enhancement

#407 Export `SetStatus` function on OnwerDBs
  token/services/owner/owner.go
Labels: enhancement

#405 ttxdb derivates: failed restart #402
  go.mod
  go.sum
  integration/token/fungible/dloghsm/topology.go
  integration/token/fungible/tests.go
  integration/token/fungible/topology.go
  integration/token/nft/topology.go
  samples/fungible/topology/orion.go
  token/core/identity/registry.go
  token/sdk/sdk.go
  token/services/auditor/auditor.go
  token/services/auditor/manager.go
  token/services/network/orion/publicparams.go
  token/services/owner/manager.go
  token/services/owner/owner.go
  tools/go.mod
  tools/go.sum
Labels: bug

#410 FTS to now use FSC Fabric Binary Only Implementation
  .github/workflows/tests.yml
  Makefile
  README.md
  ci/scripts/download_fabric.sh
  fungible.mk
  go.mod
  go.sum
  interop.mk
  samples/README.md
  samples/fungible/README.md
  samples/nft/README.md
Labels: enhancement
