Repository hyperledger-labs/fabric-token-sdk, pull requests merged in 2023-01, with the labels that each got.

#439 sender should match audit info #438
  integration/token/fungible/support.go
  integration/token/fungible/tests.go
  integration/token/fungible/views/issue.go
  integration/token/fungible/views/transfer.go
  token/core/fabtoken/deserializer.go
  token/core/fabtoken/wallet.go
  token/core/identity/msp/x509/mspx509.go
  token/core/zkatdlog/nogh/wallet.go
Labels: bug

#444 remove todos from crypto library
  cmd/tokengen/main_test.go
  integration/token/fungible/dlog/dlog_test.go
  token/core/zkatdlog/crypto/range/proof.go
  token/core/zkatdlog/crypto/setup.go
  token/core/zkatdlog/crypto/sigproof/membership.go
  token/core/zkatdlog/crypto/transfer/sender.go
  token/core/zkatdlog/crypto/validator/validator.go
Labels: cleanup

#448 ZKATDLOG: Improved VaultTokenCommitmentLoader
  integration/token/fungible/views/checks.go
  integration/token/interop/support.go
  token/core/zkatdlog/nogh/auditor.go
  token/core/zkatdlog/nogh/driver/driver.go
  token/core/zkatdlog/nogh/issuer.go
  token/core/zkatdlog/nogh/loaders.go
  token/core/zkatdlog/nogh/sender.go
  token/core/zkatdlog/nogh/service.go
  token/driver/vault.go
  token/services/certifier/interactive/service.go
  token/services/network/fabric/vault.go
  token/services/network/orion/vault.go
  token/services/vault/driver/driver.go
  token/services/vault/query/query.go
  token/vault.go
Labels: enhancement

#445 tokengen pp command suite
  cmd/tokengen/README.md
  cmd/tokengen/main.go
  cmd/tokengen/testdata/zkatdlog_pp.json
  token/core/cmd/pp/gen.go
  token/core/cmd/pp/printpp/print.go
  token/core/cmd/pp/utils.go
  token/core/fabtoken/setup.go
  token/core/zkatdlog/crypto/setup.go
  token/driver/publicparams.go
Labels: enhancement
