Repository hyperledger-labs/fabric-token-sdk, pull requests merged in 2024-06, with the labels that each got.

#642 configuration service
  docs/core-token.md
  integration/token/fungible/wmp.go
  token/config.go
  token/core/common/tms.go
  token/core/common/wallets.go
  token/core/common/wcache.go
  token/core/config/config.go
  token/core/fabtoken/driver/driver.go
  token/core/fabtoken/service.go
  token/core/tms.go
  token/core/zkatdlog/nogh/driver/driver.go
  token/core/zkatdlog/nogh/service.go
  token/core/zkatdlog/nogh/wallet.go
  token/driver/config.go
  token/driver/config/config.go
  token/driver/tms.go
  token/provider.go
  token/sdk/db/config.go
  token/sdk/sdk.go
  token/services/certifier/interactive/driver.go
  token/services/config/config.go
  token/services/config/config_test.go
  token/services/config/testdata/token0/core.yaml
  token/services/db/driver/config.go
  token/services/db/sql/driver.go
  token/services/identity/config/identity.go
  token/services/identity/config/identity_test.go
  token/services/identity/config/testdata/invalid/core.yaml
  token/services/identity/config/testdata/token0/core.yaml
  token/services/identity/msp/config/config.go
  token/services/identity/msp/idemix/lm.go
  token/services/identity/msp/rolefactory.go
  token/services/identity/msp/x509/lm.go
  token/services/identitydb/db_test.go
  token/services/network/fabric/driver.go
  token/services/network/fabric/network.go
  token/services/network/orion/driver.go
  token/services/network/orion/network.go
  token/services/selector/mailman/provider.go
  token/services/selector/sherdlock/manager.go
  token/services/selector/sherdlock/provider.go
  token/services/selector/simple/provider.go
  token/services/tokendb/db_test.go
  token/services/ttxdb/db/memory/memory_test.go
  token/services/ttxdb/db_test.go
  token/services/utils/lazygetter.go
  token/services/utils/lazyprovider.go
  token/services/utils/lazyprovider_test.go
  token/tms.go
Labels: improvements

#645 remove storage service as it is not needed anymore
  token/sdk/sdk.go
  token/sdk/storage/storage.go
  token/services/auditor/manager.go
  token/services/storage/it.go
  token/services/storage/storage.go
  token/services/tokens/manager.go
  token/services/ttx/manager.go
Labels: cleanup

#647 reduce the use of view.Identity where possible
  token/services/db/dbtest/transactions.go
  token/services/db/driver/identity.go
  token/services/db/driver/ttx.go
  token/services/db/sql/identity.go
  token/services/db/sql/transactions.go
  token/services/db/sql/wallet.go
  token/services/selector/mailman/provider.go
  token/services/tokens/storage.go
  token/services/tokens/tokens.go
  token/services/ttxdb/db.go
  token/services/ttxdb/db_test.go
Labels: cleanup

#650 stress test + audit bug fix
  integration/ports.go
  integration/token/common/topology.go
  integration/token/fungible/dlogstress/dlog_suite_test.go
  integration/token/fungible/dlogstress/dlog_test.go
  integration/token/fungible/dlogstress/support/worker.go
  integration/token/fungible/tests.go
  integration/token/fungible/topology/topology.go
  token/services/auditdb/db.go
  token/services/auditor/auditor.go
Labels: bug

#652 Separate token parsing from storage
  Makefile
  token/services/db/driver/token.go
  token/services/db/sql/identity_test.go
  token/services/db/sql/tokens.go
  token/services/tokens/storage.go
  token/services/tokens/tokens.go
  token/services/tokens/tokens_test.go
Labels: bug
