Repository hyperledger-labs/fabric-token-sdk, pull requests merged in 2024-05, with the labels that each got.

#626 cleaup service provider's use in services
  token/services/auditdb/db.go
  token/services/auditor/manager.go
  token/services/identity/storage.go
  token/services/interop/htlc/wallet.go
  token/services/network/driver/driver.go
  token/services/network/fabric/driver.go
  token/services/network/fabric/network.go
  token/services/network/network.go
  token/services/network/orion/driver.go
  token/services/network/orion/network.go
  token/services/network/orion/publicparams.go
  token/services/nfttx/qe.go
  token/services/nfttx/uniqueness/uniqueness.go
  token/services/nfttx/wallet.go
  token/services/tokendb/db.go
  token/services/tokens/manager.go
  token/services/ttx/auditor.go
  token/services/ttx/info.go
  token/services/ttx/manager.go
  token/services/ttx/metrics.go
  token/services/ttx/owner.go
  token/services/ttx/wallet.go
  token/services/ttxdb/db.go
  token/services/vault/vault.go
Labels: improvements

#630 revert changes: compute max value using big int
  cmd/tokengen/main_test.go
  cmd/tokengen/testdata/zkatdlog_pp.json
  token/core/zkatdlog/crypto/setup.go
  token/core/zkatdlog/crypto/setup_test.go
Labels: bug

#636 remove dependencies to core and driver packages
  integration/nwo/token/common/ppmgen.go
  integration/nwo/token/generators/fabtoken/fabtoken.go
  integration/nwo/token/generators/wallet.go
  token/services/identity/msp/x509/msp/config.go
  token/services/identity/msp/x509/msp/pkcs11/pkcs11.go
Labels: cleanup

#632 Sherdlock
  integration/nwo/token/orion/template.go
  token/common/core/types.go
  token/sdk/sdk.go
  token/services/db/driver/token.go
  token/services/db/sql/driver/driver.go
  token/services/db/sql/identity.go
  token/services/db/sql/identity_test.go
  token/services/db/sql/init.go
  token/services/db/sql/init_test.go
  token/services/db/sql/test_utils.go
  token/services/db/sql/tokenlock.go
  token/services/db/sql/tokens_test.go
  token/services/db/sql/transactions_test.go
  token/services/db/sql/wallet_test.go
  token/services/drivers/dbholder.go
  token/services/drivers/holder.go
  token/services/drivers/memorydriver.go
  token/services/drivers/serviceholder.go
  token/services/drivers/sqldriver.go
  token/services/nfttx/filter.go
  token/services/selector/benchmark_test.go
  token/services/selector/mailman/manager.go
  token/services/selector/mailman/provider.go
  token/services/selector/mailman/selector_simple.go
  token/services/selector/mailman/utils.go
  token/services/selector/sherdlock/inmemory/locker.go
  token/services/selector/sherdlock/manager.go
  token/services/selector/sherdlock/manager_test.go
  token/services/selector/sherdlock/provider.go
  token/services/selector/sherdlock/selector.go
  token/services/selector/simple/provider.go
  token/services/selector/simple/selector.go
  token/services/selector/testutils/test_cases.go
  token/services/selector/testutils/testutils.go
  token/services/tokenlockdb/db.go
  token/services/tokenlockdb/db/memory/memory.go
  token/services/tokenlockdb/db/sql/driver.go
  token/vault.go
Labels: improvements

#637 token selector: streamline filter interfaces
  token/selector.go
  token/services/selector/simple/selector.go
Labels: improvements

#635 clean up dependencies of sdk.go
  docs/deployment/deployment.md
  docs/design.md
  docs/imgs/deployment.png
  docs/services/storage.md
  integration/token/common/sdk/fall/sdk.go
  integration/token/common/sdk/fdlog/sdk.go
  integration/token/common/sdk/ffabtoken/sdk.go
  integration/token/common/sdk/fodlog/sdk.go
  integration/token/common/sdk/fofabtoken/sdk.go
  integration/token/common/sdk/odlog/sdk.go
  integration/token/common/sdk/ofabtoken/sdk.go
  integration/token/common/topology.go
  integration/token/dvp/dlog/dlog_test.go
  integration/token/dvp/fabtoken/fabtoken_test.go
  integration/token/fungible/dlog/dlog_test.go
  integration/token/fungible/dloghsm/dlog_test.go
  integration/token/fungible/fabtoken/fabtoken_test.go
  integration/token/fungible/mixed/mixed_test.go
  integration/token/fungible/mixed/topology.go
  integration/token/fungible/odlog/dlog_test.go
  integration/token/fungible/ofabtoken/fabtoken_test.go
  integration/token/fungible/topology/topology.go
  integration/token/interop/dlog/dlog_test.go
  integration/token/interop/fabtoken/fabtoken_test.go
  integration/token/interop/support.go
  integration/token/interop/tests.go
  integration/token/interop/topology.go
  integration/token/nft/dlog/dlog_test.go
  integration/token/nft/fabtoken/fabtoken_test.go
  integration/token/nft/odlog/dlog_test.go
  integration/token/nft/ofabtoken/fabtoken_test.go
  integration/token/nft/topology.go
  token/core/cmd/certfier/keypairgen.go
  token/core/tms.go
  token/driver/tms.go
  token/provider.go
  token/sdk/network/fetcher.go
  token/sdk/network/normalizer.go
  token/sdk/network/selector.go
  token/sdk/sdk.go
  token/sdk/tms/tms.go
  token/sdk/vault/provider.go
  token/services/certifier/dummy/driver.go
  token/services/db/sql/driver/unity/driver.go
  token/services/network/common/fetcher.go
  token/services/network/common/filter.go
  token/services/network/common/normalizer.go
  token/services/network/driver/network.go
  token/services/network/fabric/driver.go
  token/services/network/fabric/network.go
  token/services/network/network.go
  token/services/network/orion/driver.go
  token/services/network/orion/network.go
  token/services/selector/simple/inmemory/locker.go
  token/services/selector/simple/provider.go
  token/services/selector/testutils/testutils.go
  token/services/ttx/finality.go
  token/services/ttxdb/db.go
Labels: improvements
