Repository hyperledger-labs/fabric-token-sdk, pull requests merged in 2025-07, with the labels that each got.

#1126 add support for issue metadata
  token/core/common/meta/metadata.go
  token/core/common/meta/metadata_test.go
  token/core/fabtoken/v1/issue.go
  token/core/fabtoken/v1/transfer.go
  token/core/zkatdlog/nogh/v1/issue.go
  token/request.go
Labels: enhancement, token-driver

#1143 FSC dep update
  go.mod
  go.sum
  integration/token/fungible/support.go
  integration/token/fungible/views/balance.go
  integration/token/fungible/views/info.go
  token/services/identity/storage/kvs/hashicorp/go.mod
  token/services/identity/storage/kvs/hashicorp/go.sum
  token/services/network/fabric/lookup/deliveryllm.go
  tools/go.mod
  tools/go.sum
Labels: dep update

#1050 add custom application metadata to public data on ledger
  integration/token/fungible/support.go
  integration/token/fungible/views/history.go
  integration/token/fungible/views/transfer.go
  token/core/common/meta/metadata.go
  token/core/common/validator_issue.go
  token/core/common/validator_issue_test.go
  token/core/common/validator_transfer.go
  token/core/common/validator_transfer_test.go
  token/core/fabtoken/v1/validator/validator.go
  token/core/zkatdlog/nogh/v1/validator/validator.go
  token/request.go
Labels: enhancement, token-driver

#1149 nwo: do not create folders that are not used
  integration/nwo/token/common/ne.go
  integration/nwo/token/fabric/fabric.go
Labels: nwo

#1142 don't panic if the wallet is not found
  token/services/ttx/recipients.go
Labels: cleanup

#1163 development documentation
  Makefile
  README.md
  docs/development/development.md
  docs/development/general.md
  docs/development/idiomatic.md
  docs/development/linting.md
  docs/development/mock.md
  docs/development/monitoring.md
  docs/development/storage.md
  docs/development/tokengen.md
  docs/development/tools.md
  docs/development/versioning.md
Labels: documentation

#1174 introduce nocache and ristretto-based cache #1173
  go.mod
  go.sum
  token/services/db/sql/common/identity.go
  token/services/identity/provider.go
  token/services/network/common/finality.go
  token/services/tokens/tokens.go
  token/services/utils/cache/nocache.go
  token/services/utils/cache/nocache_test.go
  token/services/utils/cache/ristretto.go
  token/services/utils/cache/ristretto_test.go
Labels: performance
