Repository hyperledger-labs/fabric-token-sdk, pull requests merged in 2025-06, with the labels that each got.

#1100 upgradability: add multiplexing driver #1091
  cmd/tokengen/main_test.go
  cmd/tokengen/testdata/zkatdlog_pp.json
  integration/token/fungible/fabtoken/fabtoken_test.go
  integration/token/fungible/support.go
  integration/token/fungible/tests.go
  token/core/common/ppm.go
  token/core/fabtoken/protos-go/pp/ftpp.pb.go
  token/core/fabtoken/protos/ftpp.proto
  token/core/fabtoken/v1/driver/base.go
  token/core/fabtoken/v1/driver/deserializer.go
  token/core/fabtoken/v1/driver/driver.go
  token/core/fabtoken/v1/driver/ppm_factory.go
  token/core/fabtoken/v1/driver/ws_factory.go
  token/core/fabtoken/v1/setup/setup.go
  token/core/fabtoken/v1/setup/setup_test.go
  token/core/naming.go
  token/core/naming_test.go
  token/core/service.go
  token/core/zkatdlog/nogh/protos-go/pp/noghpp.pb.go
  token/core/zkatdlog/nogh/protos/noghpp.proto
  token/core/zkatdlog/nogh/v1/driver/base.go
  token/core/zkatdlog/nogh/v1/driver/deserializer.go
  token/core/zkatdlog/nogh/v1/driver/driver.go
  token/core/zkatdlog/nogh/v1/driver/ppm_factory.go
  token/core/zkatdlog/nogh/v1/driver/ws_factory.go
  token/core/zkatdlog/nogh/v1/setup/setup.go
  token/core/zkatdlog/nogh/v1/setup/setup_test.go
  token/driver/mock/pp.go
  token/driver/publicparams.go
  token/publicparams.go
  token/publicparams_test.go
  token/services/logging/logger.go
Labels: token-driver

#1058 Pull Request Requirements
  DEVELOPMENT.md
Labels: documentation

#1049 dlog v1 finalization: proofs must belong to the elliptic curve defined in the public parameters
  token/core/zkatdlog/nogh/v1/crypto/math/math.go
  token/core/zkatdlog/nogh/v1/crypto/rp/bulletproof.go
  token/core/zkatdlog/nogh/v1/crypto/rp/bulletproof_test.go
  token/core/zkatdlog/nogh/v1/crypto/rp/ipa.go
  token/core/zkatdlog/nogh/v1/crypto/rp/ipa_test.go
  token/core/zkatdlog/nogh/v1/crypto/rp/rangecorrectness.go
  token/core/zkatdlog/nogh/v1/crypto/rp/rp_suite_test.go
  token/core/zkatdlog/nogh/v1/transfer/transfer.go
  token/core/zkatdlog/nogh/v1/transfer/typeandsum.go
Labels: improvements

#1111 Enhance the validator context with the anchor #1075
  integration/token/fungible/views/utils.go
  token/core/common/validator.go
  token/core/common/validator_test.go
  token/core/fabtoken/v1/auditor.go
  token/core/fabtoken/v1/transfer.go
  token/core/zkatdlog/nogh/v1/audit/auditor.go
  token/core/zkatdlog/nogh/v1/auditor.go
  token/core/zkatdlog/nogh/v1/transfer.go
  token/driver/auditor.go
  token/driver/mock/ts.go
  token/driver/mock/validator.go
  token/driver/request.go
  token/driver/transfer.go
  token/driver/validator.go
  token/request.go
  token/services/auditdb/store.go
  token/services/auditor/auditor.go
  token/services/network/common/finality.go
  token/services/network/fabric/endorsement/approval.go
  token/services/network/fabric/tcc/mock/validator.go
  token/services/network/fabric/tcc/tcc.go
  token/services/tokens/tokens.go
  token/services/ttx/transaction.go
  token/services/ttxdb/store.go
  token/services/ttxdb/store_test.go
  token/stream.go
  token/stream_test.go
  token/tms.go
  token/validator.go
  token/validator_test.go
Labels: enhancement

#1068 Redeem: Issuer parameter
  integration/token/fungible/mixed/mixed_test.go
  integration/token/fungible/support.go
  integration/token/fungible/tests.go
  integration/token/fungible/views/redeem.go
  token/core/common/transfer.go
  token/core/common/transfer_test.go
  token/core/fabtoken/v1/transfer.go
  token/core/zkatdlog/nogh/v1/transfer.go
  token/services/ttx/transfer_opts.go
Labels: enhancement

#1076 Redeem integration test where the issuer is also the party that asks to redeem a token
  .github/workflows/tests.yml
  fungible.mk
  integration/token/fungible/dlog/dlog_test.go
  integration/token/fungible/tests.go
Labels: testing

#1118 QueryTransactionsParams: Filter by token type #1117 Open
  token/services/db/driver/common.go
  token/services/db/sql/common/querybuilder_test.go
  token/services/db/sql/common/tcondition.go
Labels: enhancement, db

#1119 Test FSC's PR #960
  go.mod
  go.sum
  integration/nwo/token/common/utils.go
  integration/nwo/token/fabric/fabric.go
  integration/nwo/token/fabric/template.go
  integration/token/test_utils.go
Labels: dep update

#1121 FSC #963 Dep Update
  cmd/tokengen/samples/topology/fungible.go
  go.mod
  go.sum
  integration/nwo/token/topology.go
  integration/token/common/sdk/fall/sdk.go
  integration/token/common/sdk/fdlog/sdk.go
  integration/token/common/sdk/ffabtoken/sdk.go
  integration/token/common/topology.go
  integration/token/dvp/dlog/dlog_test.go
  integration/token/dvp/fabtoken/fabtoken_test.go
  integration/token/dvp/topology.go
  integration/token/fungible/dlog/dlog_test.go
  integration/token/fungible/dloghsm/dlog_test.go
  integration/token/fungible/dlogstress/dlog_test.go
  integration/token/fungible/fabtoken/fabtoken_test.go
  integration/token/fungible/mixed/mixed_test.go
  integration/token/fungible/update/update_test.go
  integration/token/interop/dlog/dlog_test.go
  integration/token/interop/fabtoken/fabtoken_test.go
  integration/token/nft/dlog/dlog_test.go
  integration/token/nft/fabtoken/fabtoken_test.go
  token/sdk/dig/sdk.go
Labels: dep update
