Repository hyperledger-labs/fabric-token-sdk, pull requests merged in 2025-09, with the labels that each got.

#1216 enhanced redeem: make issuer signature optional #1134
  cmd/tokengen/cobra/pp/fabtokenv1/gen.go
  cmd/tokengen/cobra/pp/zkatdlognoghv1/gen.go
  token/core/common/ppm.go
  token/core/common/transfer.go
  token/core/common/transfer_test.go
  token/core/fabtoken/v1/setup/setup.go
  token/core/fabtoken/v1/setup/setup_test.go
  token/core/fabtoken/v1/validator/validator_transfer.go
  token/core/zkatdlog/nogh/v1/setup/setup.go
  token/core/zkatdlog/nogh/v1/setup/setup_test.go
  token/core/zkatdlog/nogh/v1/transfer.go
  token/core/zkatdlog/nogh/v1/validator/validator_transfer.go
  token/provider.go
  token/publicparams.go
  token/publicparams_test.go
Labels: enhancement

#1221 extensions
  docs/core/extension/zkatdlog/nogh/v2/driver/driver.go
  go.mod
  go.sum
  token/core/fabtoken/v1/driver/driver.go
  token/core/zkatdlog/nogh/v1/driver/driver.go
  token/services/config/configuration.go
  token/services/config/service.go
  token/services/config/service_test.go
  token/services/identity/storage/kvs/hashicorp/go.mod
  token/services/identity/storage/kvs/hashicorp/go.sum
Labels: enhancement

#1147 idemix race checks
  go.mod
  go.sum
  token/services/identity/idemix/cache/cache_test.go
  token/services/identity/idemix/km_bench_test.go
  token/services/identity/idemix/km_test.go
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/ca/ca/IssuerPublicKey
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/ca/ca/IssuerSecretKey
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/ca/ca/RevocationKey
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/ca/msp/IssuerPublicKey
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/ca/msp/RevocationPublicKey
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/idemix/msp/IssuerPublicKey
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/idemix/msp/RevocationPublicKey
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/idemix/user/SignerConfig
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/idemix2/msp/IssuerPublicKey
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/idemix2/msp/RevocationPublicKey
  token/services/identity/idemix/testdata/bls12_381_bbs_gurvy/idemix2/user/SignerConfig
  token/services/identity/idemix/testdata/generate.go
  token/services/identity/storage/kvs/hashicorp/go.mod
  token/services/identity/storage/kvs/hashicorp/go.sum
  token/services/identity/storage/kvs/tracker.go
Labels: bug, race

#1220 Bump FSC
  go.mod
  go.sum
  token/services/identity/storage/kvs/hashicorp/go.mod
  token/services/identity/storage/kvs/hashicorp/go.sum
Labels: dep update
